### ISSUE TITLE
Group.characteristic - bloc critere inclusion exclusion

### ISSUE THREAD

**Issue by paulineheurtebise** [DNUM-SocialGouv/eclaire#142]
Dans l'élément caracteristic, il ne peut pas il y avoir de bloc (valueCodeableConcept) de type Inclusion criteria ou Exclusion criteria. 
La notion d'inclusion ou d'exclusion est déjà portée par l'attribut exclude. 

![image](https://github.com/DNUM-SocialGouv/eclaire/assets/122790741/4d2cf8b2-fdfd-4229-9866-4b99f48a0b66)

Ces deux blocs sont donc à mon sens à supprimer.

**Comment by sbedeau** [comment]
traité par #152
