### ISSUE TITLE
Group.characteristic.code - Contenu du valueSet

### ISSUE THREAD

**Issue by paulineheurtebise** [DNUM-SocialGouv/eclaire#143]
Quelles sont les valeurs possibles pour le type de Group.characteristic ? 

![image](https://github.com/DNUM-SocialGouv/eclaire/assets/122790741/aa8f31f0-7ed4-42a0-becf-a072c7b97ccc)

D'après l'exemple, les valeurs possibles sont : 
Gender
Study Population
Research Study Group Category

Je pense qu'il est nécessaire d'ajouter une valeur autre ou inderminé ? 

Faut - il également ajouter une valeur pour l'age ?

**Comment by paulineheurtebise** [comment]
Réunion du 08/01 : contenu du CodeSystem

- Gender
- Study Population
- Research Study Group Category
- Age
- Other

**Comment by sbedeau** [comment]
traité par #152
