### ISSUE TITLE
Information portée par le champs "Text" dans les attributs de type CodeableConcept

### ISSUE THREAD

**Issue by paulineheurtebise** [DNUM-SocialGouv/eclaire#144]
Les attributs de type [CodeableConcept](https://build.fhir.org/datatypes.html#CodeableConcept) sont par nature des attributs codés. Ce type de donné permet une souplesse en permettant de renseigner le champs "text", c'est à a dire de saisir une information en texte libre plutôt que de choisir une valeur dans les codes possibles ou permet d'apporter des nuances vis à vis du code sélectionné. 

Pour être conforme au standard, le champ "text" ne peut pas porter une autre information. 

![image](https://github.com/DNUM-SocialGouv/eclaire/assets/122790741/4efce5cc-3a3b-45af-9c3a-5ddfd3580873)

Par exemple, dans Group.characteristic, le champs "text" n'a pas vocation a porter le type de characteristic décrite. 
C'est une information en tant que telle qui doit être portée par l'attribut "Group.characteristic.code"
![image](https://github.com/DNUM-SocialGouv/eclaire/assets/122790741/18368b0d-ec4f-499e-b393-040f3b6e8546)

Le champs "text" # "display"
Display = libellé associé au code. 
Text = du texte libre --> "The codes from the terminologies do not always capture the correct meaning with all the nuances of the human using them, or sometimes there is no appropriate code at all. In these cases, the text is used to capture the full meaning of the source"

**Comment by sly-kereval** [comment]
Pour compléter, voici un exemple avec 2 critères : 

```json
"characteristic" : [
  {
    "code": {
        "coding": {
            "code": "gender",
            "system": "Pas_encore_créé", 
            "display": "Gender"
        }    
    },
    "valueCodeableConcept": {
      "coding": {
        "code": "female",
        "system": "http://hl7.org/fhir/ValueSet/administrative-gender", 
        "display": "Female",
      }
    },
    "exclude": false
  },
  {
    "code": {
        "coding": {
            "code": "other",
            "system": "Pas_encore_créé", 
            "display": "Other"
        }    
    },
    "valueCodeableConcept": {
      "text": "Femme atteinte de cancer du sein stade 2"
    }, 
    "exclude": true
  }
]
```

**Comment by sbedeau** [comment]
Bonjour, 
La demande est bien prise en compte. Nous pensons commencer les développements pendant la semaine du 08/01. 
Pouvez-vous nous mettre le system à disposition svp ?

**Comment by paulineheurtebise** [comment]
Bonjour, 
Pour mettre à disposition le code system nous avons besoin de connaitre le contenu cf #143. 
Merci !

**Comment by sdemeyANS** [comment]
Bonjour
issue https://github.com/ansforge/IG-fhir-essais-cliniques/pull/104 traitée pour info

**Comment by paulineheurtebise** [comment]
Hello, 
Dans les json le nom des slices n'apparait pas. 
L'idée du slice est de découpée la liste en sous lits pour ajouter des contraintes ou une signification supplémentaire. 
Cependant cela n'a pas d'impact sur le format de la ressource en json.
Je remets le paragraphe de la[spec FHIR](https://build.fhir.org/profiling.html#slicing) qui le précise : 
![image](https://github.com/DNUM-SocialGouv/eclaire/assets/122790741/01abc552-079b-4286-872a-cb24d6011af4)
