### ISSUE TITLE
erreur validator https://eclaire-api.osc-fr1.scalingo.io/R4/ResearchStudy/2022-500642-25-00

### ISSUE THREAD

**Issue by sdemeyANS** [DNUM-SocialGouv/eclaire#146]
Bonjour,

Cette ressource 2022-500642-25-00 ne passe pas la validation.
<img width="458" alt="image" src="https://github.com/DNUM-SocialGouv/eclaire/assets/117643165/4a6d31a1-168d-4d0c-bb0d-0c332bf3e1a9">

Le problème se situe ici :
<img width="304" alt="image" src="https://github.com/DNUM-SocialGouv/eclaire/assets/117643165/2b16c3ce-ce2e-42c7-b380-9ec7b4214e14">

A noter que d'autres ressources ont la même erreur.

S'il n'y a pas de data pour MedDRA il ne faut rien transmettre. Ce n'est pas obligatoire.

Bien cordialement,

**Comment by sbedeau** [comment]
#147 a pris en compte cette demande 
cf https://github.com/DNUM-SocialGouv/eclaire/pull/147/files#diff-2dd504c13aaaadabb44dbfa4e195bf0df4d66c4f628ec6579b2662591387a55eR211
