### ISSUE TITLE
[API FHIR] id et identifier

### ISSUE THREAD

**Issue by sdemeyANS** [DNUM-SocialGouv/eclaire#72]
Bonjour,
l'id et l'identifier sont les mêmes (exemple ressource 2022-500520-30-00)
Est-ce normal ?
Pour l'identifier un system est souhaité, mais peut être esct-ce en lien avec l'issue #66 

Bien à vous,

Sylvain

**Comment by NerOcrO** [comment]
Oui c'est normal, on a prit partie d'avoir le même pour une question de simplicité au niveau de notre base de données.
